package com.eternal130.mobends_tfcp_compat;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

/**
 * Client proxy. The Mixin on {@code RenderClothing.doRender} auto-registers via the mixin config
 * generated by the build script, so there is nothing to wire up here at runtime. We only log
 * whether both target mods were detected, which helps users diagnose missing-dependency installs.
 */
public class ClientProxy extends CommonProxy {

    @Override
    public void preInit(FMLPreInitializationEvent event) {
        boolean mobends = Loader.isModLoaded(MoBendsTFCPCompat.MODID_MOBENDS);
        boolean tfcp = Loader.isModLoaded(MoBendsTFCPCompat.MODID_TFCP);
        if (mobends && tfcp) {
            MoBendsTFCPCompat.LOG.info("MoBends TFCP Compat: both mods present, Mixin will patch RenderClothing.");
        } else {
            MoBendsTFCPCompat.LOG.warn(
                "MoBends TFCP Compat: inactive (mobends={}, tfcp={}). The mod needs BOTH to do anything.",
                mobends,
                tfcp);
        }
    }

    @Override
    public void init(FMLInitializationEvent event) {}

    @Override
    public void postInit(FMLPostInitializationEvent event) {}
}
